name: Run Renovate Bot - Samples

on:
  schedule:
    - cron: '0 */4 * * *' # run every 4 hours
  workflow_dispatch:

jobs:
  renovate-samples:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Cache renovate cache
        uses: actions/cache@v5
        with:
          path: |
            .renovate-cache-samples
            .renovate-tmp-samples
          key: ${{ runner.os }}-renovate-samples-
          restore-keys: |
            ${{ runner.os }}-renovate-samples-


      - name: show renovate cache dir
        run: tree .renovate-cache-samples

      - name: Run Renovate
        run: ./run-in-parallel
        env:
          FORCE_COLOR: 3
          SPECMATIC_GITHUB_TOKEN: ${{ secrets.SPECMATIC_GITHUB_TOKEN }}
          SPECMATIC_REPOSILITE_USERNAME: ${{ secrets.SPECMATIC_REPOSILITE_USERNAME }}
          SPECMATIC_REPOSILITE_TOKEN: ${{ secrets.SPECMATIC_REPOSILITE_TOKEN }}
          SPECMATIC_GITHUB_USER: ${{ vars.SPECMATIC_GITHUB_USER }}
          RENOVATE_CONFIG_FILE: ./renovate.js
          RENOVATE_TMPDIR: .renovate-tmp-samples
          RENOVATE_CACHE_DIR: .renovate-cache-samples
          LOG_LEVEL: debug
          RENOVATE_ADDITIONAL_CONFIG_FILE: ./renovate.samples.js


      - name: show renovate cache dir
        run: tree .renovate-cache-samples
