name: Run Renovate Bot - Main Repos

on:
  schedule:
    - cron: '0 */6 * * *' # run every 6 hours
  workflow_dispatch:

jobs:

  renovate-main-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install npm packages
        run: npm install

      - name: Cache renovate cache
        uses: actions/cache@v5
        with:
          path: |
            .renovate-cache-main
            .renovate-tmp-main
          key: ${{ runner.os }}-renovate-main-
          restore-keys: |
            ${{ runner.os }}-renovate-main-

      - name: Workaround for checkout v6
        run: |
          git config --unset-all http.https://github.com/.extraheader || true

      - name: Run Renovate
        run: |
          ./run-in-parallel
        env:
          FORCE_COLOR: 3
          SPECMATIC_GITHUB_TOKEN: ${{ secrets.SPECMATIC_GITHUB_TOKEN }}
          SPECMATIC_REPOSILITE_USERNAME: ${{ secrets.SPECMATIC_REPOSILITE_USERNAME }}
          SPECMATIC_REPOSILITE_TOKEN: ${{ secrets.SPECMATIC_REPOSILITE_TOKEN }}
          SPECMATIC_GITHUB_USER: ${{ vars.SPECMATIC_GITHUB_USER }}
          RENOVATE_CONFIG_FILE: ./renovate.js
          RENOVATE_TMPDIR: .renovate-tmp-main
          TMPDIR: .renovate-tmp-main
          RENOVATE_CACHE_DIR: .renovate-cache-main
          LOG_LEVEL: debug
          RENOVATE_ADDITIONAL_CONFIG_FILE: ./renovate.main.js
